name: car_maintenance_tracker
description: Araba bakım takip uygulaması

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_riverpod: ^2.4.9

  # Database & Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # Supabase
  supabase_flutter: ^2.8.2

  # Date & Time
  intl: ^0.18.1

  # Networking (gelecekte API entegrasyonu için)
  http: ^1.1.0
  dio: ^5.3.2

  # Utils
  uuid: ^4.1.0

  # Icons & UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

# Android için
android:
  package: com.yourdomain.carservice
  versionCode: 1
  versionName: "1.0.0"
